"use client";
import { headers, rows } from "@/mockData/data";
import Head from "next/head";
import DataTable from "@/components/DataTable";

const Home = () => {
  return (
    <>
      <Head>
        <title>DataTable</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <DataTable sortable caption="Bookings" headers={headers} rows={rows} />
      </main>
    </>
  );
};

export default Home;
